### ISSUE TITLE
read-only flag on directories shall be ignored

### ISSUE THREAD

**Issue by blizzz** [icewind1991/SMB#103]
From https://github.com/nextcloud/server/issues/23462:

> Even though this sounds like expected behaviour, it actually is a bug and should be changed.
> 
> > Unlike the Read-only attribute for a file, the Read-only attribute for a folder is typically ignored by Windows, Windows components and accessories, and other programs. For example, you can delete, rename, and change a folder with the Read-only attribute by using Windows Explorer.
> 
> Reference: http://support.microsoft.com/kb/326549

by @samanyu7

@icewind1991

**Comment by icewind1991** [comment]
I'm fine with ignoring the flag but that should be done in the `files_external` code, not in this library.

**Comment by blizzz** [comment]
According to that issue the relevant check is in src/Native/NativeFileInfo.php with the proposed patch at https://github.com/nextcloud/server/issues/23462#issuecomment-723676958

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/26292
