### ISSUE TITLE
[Enhancement] Getting the acls of a smb file or folder

### ISSUE THREAD

**Issue by jvillafanez** [icewind1991/SMB#16]
There are some user experience issues with the current permission handling.

In a windows with several user accounts, a user can share the contents with other users granting them read-only permissions. Accessing with the library to that share with the both user accounts reports the same permissions ("dos mode") even though the permissions are different and the second user can't upload content to the folder (no complains since it's how it works and the smbclient reports the same).
However, this creates confusion to the end user.

It's seems that getting the acls of the file / folder is the way to go to get a smoother user experience.

To get the acls, I've gather some information that might be useful:

> For command line: http://www.samba.org/samba/docs/man/manpages/smbcacls.1.html
> For libsmbclient:
>     ```
> smbclient_getxattr($q, 'smb://server/share/path', 'system.nt_sec_desc.acl.*+');
> server\user1:0/3/0x001200a9,NT AUTHORITY\SYSTEM:0/19/0x001f01ff,BUILTIN\Administradores:0/19/0x001f01ff,server\admin:0/19/0x001f01ff
>     ´´´
> Mask information: http://msdn.microsoft.com/en-us/magazine/cc982153.aspx (Relevant information in figureB Specific Rights for Files and Directories)

**Comment by icewind1991** [comment]
acls are exposed with 3.2.0 using `IFileInfo::getAcls()`

**Comment by icewind1991** [comment]
acls are exposed with 3.2.0 using `IFileInfo::getAcls()`
