### ISSUE TITLE
Connection error handling in native

### ISSUE THREAD

**Issue by jvillafanez** [icewind1991/SMB#20]
With the windows server down, trying to connect to the server with the library seems to throw a generic exception.

It might be a good idea to throw a connectionException for these cases (it seems the best exception to throw from the current list)

The relevant error codes are:
* 110 	Connection timed out
* 111 	Connection refused
* 112 	Host is down
* 113  No route to host

**Comment by icewind1991** [comment]
Fixed with c8a93a9033be3f42527a82fe9df28d6fce326afe
