### ISSUE TITLE
Reference issue owncloud/core #14347: fresh install stopped working w/ files_external - SMB

### ISSUE THREAD

**Issue by mmattel** [icewind1991/SMB#23]
In reference to: https://github.com/owncloud/core/issues/14347

This is the result of the requested test:

sudo phpunit
PHPUnit 4.5.0 by Sebastian Bergmann and contributors.
Configuration read from /var/www/SMB/tests/phpunit.xml
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 63 / 300 ( 21%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 126 / 300 ( 42%)
SSSSSSSSSSSSSSSSSSSS..........ES..

It took a while from ES. to ES..
There were no further messages

**Comment by mmattel** [comment]
are there any news?
my dev environment is with regards to smb still not working bebause of this...

**Comment by mmattel** [comment]
I have made some tests.
First I added some log writing code to debug properly:

	public function stat($path) {
		$escapedPath = $this->escapePath($path);
    \OC_Log::write('allinfo normal', $path, \OC_Log::WARN);
    \OC_Log::write('allinfo escaped', $escapedPath, \OC_Log::WARN);
		$output = $this->execute('allinfo ' . $escapedPath);

The result was:

``Warning 	allinfo normal   	  / 	2015-04-02T12:30:24+00:00``
``Warning 	allinfo escaped 	"" 	2015-04-02T12:30:24+00:00``

Then I did some furter tests connecting via two terminals one to a native MS server, one to a non MS SMB server:

Level | Windows | non Windows
------------ | ------------- | --------------
Root | \ or "" | .
Subfolder | \ or "" | . or \ or ""

If you use ``allinfo ""`` and get a single line response like ``NT_STATUS_OBJECT_NAME_NOT_FOUND getting alt name for \`` you need to redo the allinfo query with ``allinfo "."``
The output I have seen is either single lined (error above) or multilined (then it is ok)

Then I added the following, check if $output has less than 2 entries and redo with a different allinfo parameter:

                $output = $this->execute('allinfo ' . $escapedPath);
                if (count($output) < 2) {
                        $output = $this->execute('allinfo ' . '"."');
                }
                if (count($output) < 3) {
                        $this->parseOutput($output, $path);
                }

And voila, it works, tested with both server types :smile:

**Comment by mmattel** [comment]
Next:
After the scanning of the SMB shares started, the load on the cpu´s raised to 100% (htop) and I have 33 processes: ``smbclient --authentication-file=/proc/self/fd/3 //xxxx/yyyy``
Running now for more than 2h
Looking if there is a file or directory in /proc/self/fd/, I found only following content, but no "3":
![image](https://cloud.githubusercontent.com/assets/3321281/6968196/17cc2680-d965-11e4-997c-d22fdf7b9fd2.png)

Plus, there are recurring and really many Errors in the oC log:

Error	PHP	Undefined offset: 1 at /var/www/xxxx/apps/files_external/3rdparty/icewind/smb/src/Parser.php#94

As I have added the patch code above, line 94 points now to the list($name... statement:

        public function parseStat($output) {
                $mtime = 0;
                $mode = 0;
                $size = 0;
                foreach ($output as $line) {
                        list($name, $value) = explode(':', $line, 2);
                        $value = trim($value);
                        if ($name === 'write_time') {
                                $mtime = strtotime($value);
                        } else if ($name === 'attributes') {
                                $mode = hexdec(substr($value, 1, -1));
                        } else if ($name === 'stream') {
                                list(, $size,) = explode(' ', $value);
                                $size = intval($size);
                        }
                }

It seems, that explode has to manage $lines which seem to return an array with only one item or non item.

I will change the list statement to this code and see if it is working

    $words = explode(':', $line, 2);
    $name = isset($words[0]) ? $words[0] : '';
    $value = isset($words[1]) ? $words[1] : '';

**Comment by Xenopathic** [comment]
@mmattel PS: `/proc/self` always points to the current process, which if you `ls` it will be equivalent to `/proc/<pid-of-ls>`, not `/proc/<pid-of-smbclient>`. You need to get the actual PID of the smbclient process and look at `/proc/<pid>`.

**Comment by mmattel** [comment]
Ok, thanks for explaining.
I will do a PR today based on the finding above.
Would be happy that this gets reviewed and merged quickly

**Comment by mmattel** [comment]
For your info:

After applying the patch I created, plus applying https://github.com/icewind1991/SMB/pull/22 (fix close connection), resetting my instance and database, adding a smb sharea and let it scan, everything worked perfect. CPU was down even during the scan itself, only some smbclient processes running in parallel (was too quick to count, maybe it was only one...), scanning of >19.000 files was done in less a minute :smile:

**Comment by mmattel** [comment]
#27 and #25 do fix the problem and have been merged.
waiting for beeing forwarded to owncloud.
