### ISSUE TITLE
Missing connect() call in NativeShare.php prevent success file delete

### ISSUE THREAD

**Issue by mwehr** [icewind1991/SMB#31]
Hi,

I came across a problem within the del($path) function in NativeShare.php at line 151.
I think there is a $this->connect(); call missing before the unlink() call.
This was the solution in my case.

regards
Mario

**Comment by icewind1991** [comment]
Fixed with 545a95443a7bf8f605b5b76de1aaeed7e779cb8e

Thanks for reporting the issue
