### ISSUE TITLE
check for non-smb error messages connect

### ISSUE THREAD

**Issue by marcin-gryszkalis** [icewind1991/SMB#39]
When there are problems with file descriptors (see issue #38) one can get other kind of error message, eg.
`ERROR: Unable to open credentials file!`
and it's not recognized.

**Comment by icewind1991** [comment]
Fixed with https://github.com/icewind1991/SMB/commit/a07a5ad2ec0b8cd11a478f3e8f6c62647c4c84de

Any output in stderr is now added to the exception message
