### ISSUE TITLE
Bail out if fwrite fails

### ISSUE THREAD

**Issue by PVince81** [icewind1991/SMB#40]
See https://github.com/icewind1991/SMB/blob/v1.0.4/src/NativeShare.php#L203

If fwrite fails, need to bail out of the loop to avoid flooding logs.

**Comment by PVince81** [comment]
Also if "fopen" fails / returns a non-resource, need to bail out to and not enter the loop.

**Comment by icewind1991** [comment]
Fix is here: https://github.com/icewind1991/SMB/pull/41
