### ISSUE TITLE
Please, allow recent icewind/streams

### ISSUE THREAD

**Issue by DavidPrevot** [icewind1991/SMB#42]
Hi,

`icewind/smb` currently requires `icewind/streams` as `0.2.*`, it would be nice to make it compatible with the current `0.3` version. ownCloud currently ship with two different versions of `icewind/streams`, it may not be in the best interest of everyone.

Regards

David

**Comment by icewind1991** [comment]
Fixed with 67b4026e70ba4c26344f7f51619eaeaf371f8f9a
