### ISSUE TITLE
Throws error on upload

### ISSUE THREAD

**Issue by z013j4k** [icewind1991/SMB#48]
Hi,
I'm getting error while trying to upload file as given in example.php by just changing test value to actual value. Error is here:
Fatal error: Uncaught exception 'Icewind\SMB\Exception\ConnectException' with message 'Unknown error (sh: stdbuf: command not found)' in /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php:86 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php(50): Icewind\SMB\Connection->unknownError(false) #1 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Share.php(379): Icewind\SMB\Connection->read() #2 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Share.php(237): Icewind\SMB\Share->execute('put "/Applicati...') #3 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/example.php(15): Icewind\SMB\Share->put('/Applications/X...', 'example.php') #4 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php on line 86

Can someone help me on this?

Thanks in advance
MM

**Comment by icewind1991** [comment]
since 1.1.0 `stdbuf` is required (to handle output buffering for the `notify` command)

I'll change it to make it an optional dependency (and disable `notify` if it's not available)

**Comment by icewind1991** [comment]
Fixed with 2a101e73bc6a354eab8c1dd6f7d113af63e255e8

**Comment by icewind1991** [comment]
fix is released with 1.1.1

**Comment by z013j4k** [comment]
@icewind1991, Thanks for quick fix but this time I'm getting different error from new changes made. Not sure what could be the issue but getting error on upload something like:
Fatal error: Uncaught exception 'Icewind\SMB\Exception\ConnectException' with message 'Unknown error (sh: -W: command not found)' in /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php:86 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php(50): Icewind\SMB\Connection->unknownError(false) #1 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Share.php(386): Icewind\SMB\Connection->read() #2 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Share.php(239): Icewind\SMB\Share->execute('put "/Applicati...') #3 /Applications/XAMPP/xamppfiles/htdocs/SMB-master/example.php(15): Icewind\SMB\Share->put('/Applications/X...', 'example.php') #4 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/SMB-master/src/Connection.php on line 86
