### ISSUE TITLE
Ignore read-only attribute on folders

### ISSUE THREAD

**Issue by PVince81** [icewind1991/SMB#50]
Ignore read-only attribute on folders ("DR" attributes) and consider such folders as if they were read-write, to match the way Windows does it.

Ref: https://github.com/owncloud/core/issues/24608#issuecomment-226566095
And https://support.microsoft.com/en-us/kb/326549

@cdamken @jvillafanez @icewind1991 does this make sense ?

**Comment by PVince81** [comment]
Note: I suspect there might be a difference between read-only permisisions on **folders** and read-only permissions on **shares**. On shares we should probably still respect it, but not on folders.

**Comment by jvillafanez** [comment]
I'd rather handle this at the app level, not here. Unless we can detect we're connecting to a windows machine (which I doubt), I'd rather forward the permissions to the app, and let the app handle them as it wish.

Handle the permissions here is risky.

**Comment by icewind1991** [comment]
I agree that this should be handled at the app level

**Comment by cdamken** [comment]
I don't know how can be handled. For me is important that oC reach the storage (SMB/CIFS/WND) like the clients (Windows/Mac/Linux)

@felixboehm what do you think

**Comment by alankeny** [comment]
I don't know how this should be handled either, but I'd like to clarify the terminology.  Files and folders have both permissions and attributes.  Shares have their own permissions.  As far as I know in most situations permissions and attributes are not related.

The read-only **attribute** on a folder does not mean that the folder is read-only.  It means that it's a special folder that has had its view customized in Windows Explorer.  This issue only refers to the read-only **attribute** on a folder.

**Comment by PVince81** [comment]
Test results here: https://github.com/owncloud/core/issues/24608#issuecomment-228727364

Turns out Mac and smbclient do allow uploading into read-only folders...

**Comment by jvillafanez** [comment]
To give another reason to implement this at app level, the read-only permission could be used to show a custom icon for the folder, or to hide some of the contents of the folder, such as the desktop.ini file. Similar things can be applied for the system and archived attributes. These possiblities are cut off if we manipulate the attributes here.

If the libsmbclient library doesn't drop this at his level, I don't think we should drop it in the middle.

**Comment by felixboehm** [comment]
@jvillafanez what do you suggest then to solve this?

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/24608#issuecomment-228738481

@felixboehm follow up here https://github.com/owncloud/core/issues/24608#issuecomment-228738481
The workaround will be added in the SMB storage implementation instead of the library
