### ISSUE TITLE
Convert tabs to spaces

### ISSUE THREAD

**Issue by raffis** [icewind1991/SMB#71]
Do u mind converting tabs to spaces? It is a nightmare to work with "tabbed" code.
Maybe add a config for [editorconfig](https://editorconfig.org/) or enforce code policy with phpcs.

**Comment by icewind1991** [comment]
I've added a phpcs config and exported my ide's code style as editorconfig.
I'll enforce the code style once travis stops erroring out.

As for tabs vs spaces, I personally prefer tabs and hopefully the above will make it easier to work with them
