### ISSUE TITLE
No valid backend available, ensure smbclient is in the path or php-smbclient is installed

### ISSUE THREAD

**Issue by hamidadervic** [icewind1991/SMB#80]
I am trying to connect to an SMB server and upload a file (via windows 10, laravel application).
Steps done:
1. Installed package via composer 
2. Included in the file:
      use Icewind\SMB\ServerFactory;
      use Icewind\SMB\BasicAuth;
3. Called:
      $serverFactory = new ServerFactory();
      $auth = new BasicAuth($fileShareUsername, 'workgroup', $fileSharePassword);
      $server = $serverFactory->createServer('localhost', $auth);
       $share = $server->getShare($myFileSharePath);

Error message I got:
"No valid backend available, ensure smbclient is in the path or php-smbclient is installed"

Is this really related to the package or other things?

**Comment by cowai** [comment]
@hamidadervic Yes. You need either the module php-smbclient or the command line tool smbclient installed.

**Comment by hamidadervic** [comment]
On my side (Windows)?
Is there a link with instruction how I should do it?

**Comment by cowai** [comment]
@hamidadervic Sorry I have no knowledge of doing that on windows.
