### ISSUE TITLE
Problems with calling the Icewind class

### ISSUE THREAD

**Issue by a7mad7aydar** [icewind1991/SMB#82]
Hello guys,

I downloaded your respository to access data on an SMB server in our network. I only use windows servers here and always get the following error:

Fatal error: Uncaught Error: Class 'Icewind\SMB\BasicAuth' not found in C:\path\in\server\examples.php:12 Stack trace: #0 {main} thrown in C:\path\in\server\examples.php on line 12

Here's the code, which is basically the example.php file from your respository:

`<?php
use Icewind\SMB\ServerFactory;
use Icewind\SMB\BasicAuth;
require_once('vendor/autoload.php');

$host = 'xxx.xxx.xxx.xxx:pp';
$user = 'usr';
$workgroup = 'grp';
$password = 'pass';
$share = '\\\\link\to\folder/';

$auth = new \Icewind\SMB\BasicAuth($user, $workgroup, $password);
$serverFactory = new \Icewind\SMB\ServerFactory();

$server = $serverFactory->createServer($host, $auth);

$share = $server->getShare($share);

$files = $share->dir('/');
foreach ($files as $file) {
	echo $file->getName() . "\n";
}
?>`

**Comment by NiklasBr** [comment]
The code example uses [Composer](https://getcomposer.org/) to install this library, it seems from your description you just installed the library as-is? Is that correct?

**Comment by a7mad7aydar** [comment]
Yep! I actually found some other solution for my SMB problem, but I installed this lib with composer for future use. Thanks for the comment!
