### ISSUE TITLE
smbclient notify error on 4.7.6 Ubuntu 18.04

### ISSUE THREAD

**Issue by Jogoedota** [icewind1991/SMB#89]
When i connect to a fileserver using SMB2 and use the "notify /" command, i get the error "NT_STATUS_REVISION_MISMATCH". 

smbclient version: 4.7.6-Ubuntu
Ubuntu 18.04
Fileserver is Windows Server 2012

Is there anything I can do to fix this? Using it for Nextcloud notify setup.

**Comment by icewind1991** [comment]
smbclient only supports using notify with smb2/smb3 from version 4.7.8/4.8.1, unfortunately, you'll either have to upgrade smbclient or reply on smb1 for notify
