### ISSUE TITLE
Get server from share

### ISSUE THREAD

**Issue by hendrikbl** [icewind1991/SMB#91]
Simple Question: Is there a way to retrieve the server of a share instance?

The `NativeShare` does have a server property but its private. So I'm struggling to get the server from it. My goal is to get the complete url to a file or directory from a Share instance. Example: `server/share/path/to/file/`. 

Any help is appreciated.

**Comment by icewind1991** [comment]
Fixed with ed09f6c, not sure when I'll push a new release though

**Comment by icewind1991** [comment]
This has been released with 3.2.5
